Security
aksoli666/online-book-store pull request #12
Opened 2024-04-30 13:09 UTC by aksoli666

+added spring-boot-starter-security
+added SecurityConfig class with PasswordEncoder and SecurityFilterChain beans +implemented UserDetails interface in the User class +added the implementation for UserDetailsService interface +added Role entity
+added RoleRepository
+added field to the User entity: Set<Role> roles
+added liquibase changesets
+used @PreAuthorize

2024-05-01 05:32 UTC, Elena-Bruyako requested changes

2024-05-01 05:32 UTC, Elena-Bruyako commented on src/main/java/online/book/store/model/User.java
> +public class User implements UserDetails {
You have @SQLRestriction(value = "is_deleted = FALSE"), but there is no isDeleted field

2024-05-01 14:14 UTC, aksoli666 commented on src/main/java/online/book/store/model/Role.java
> +    @Column(nullable = false, unique = true, columnDefinition = "varchar(255)")
Made the name of the role unique because it was specified in the task.
"Add Role entity with the following fields:
id (Long, PK)
name (RoleName, not null, unique) (RoleName is enum)". 
About columnDefinition i understood.

2024-05-02 07:21 UTC, Elena-Bruyako approved these changes

2024-05-03 10:09 UTC, merged