Security / JWT
aksoli666/online-book-store pull request #13
Opened 2024-05-03 11:12 UTC by aksoli666

+Added the following method to the AuthenticationController: public UserLoginResponseDto login(UserLoginRequestDto request) 
+Created AuthenticationService, JwtAuthenticationFilter, JwtUtil classes
+ /auth/login public available 
+Used new filter in the SecurityFilterChain bean
+Used data validation in the new DTO classes

2024-05-03 11:30 UTC, kerrrusha requested changes

2024-05-03 11:30 UTC, kerrrusha commented on src/main/java/online/book/store/filter/JwtAuthFilter.java
> +            return bearerToken.substring(7);
magic number, just use length of `"Bearer "` constant

2024-05-03 11:30 UTC, kerrrusha commented on src/main/java/online/book/store/filter/JwtAuthFilter.java
> +        if (bearerToken != null && bearerToken.startsWith("Bearer ")) {
should be constants

2024-05-03 11:30 UTC, kerrrusha commented on src/main/java/online/book/store/OnlineBookStoreApplication.java
> +        System.out.println("OnlineBookStoreApplication started");
spring already prints that, moreover, for logging its better to use `@Slf4j` annotation and `log.info("your message")`
```suggestion
```

2024-05-04 11:05 UTC, okuzan approved these changes

2024-05-04 11:05 UTC, okuzan commented on src/main/java/online/book/store/filter/JwtAuthFilter.java
> +    private static final int BEARER_PREFIX_LENGTH = BEARER_PREFIX.length();
no need to make it a constant too, can use it in-place :)

2024-05-06 08:33 UTC, merged