Spring Boot practice
aksoli666/online-book-store pull request #15
Opened 2024-05-08 12:15 UTC by aksoli666

+added ShoppingCart and CartItem model

2024-05-08 12:51 UTC, kerrrusha requested changes

2024-05-08 12:51 UTC, kerrrusha commented on src/main/java/online/book/store/model/CartItem.java
> +    @ManyToOne
join column?

2024-05-08 12:51 UTC, kerrrusha commented on src/main/java/online/book/store/model/CartItem.java
> +    @NotNull
is redundant. such annotations are used for validation DTOs, not entities
```suggestion
```

2024-05-08 12:51 UTC, kerrrusha commented on src/main/java/online/book/store/model/CartItem.java
> +    @NotNull
```suggestion
    @ManyToOne
    private Book book;
    @Column(nullable = false)
```

2024-05-08 12:51 UTC, kerrrusha commented on src/main/java/online/book/store/model/CartItem.java
> +    @ManyToOne
join column?

2024-05-08 12:51 UTC, kerrrusha commented on src/main/java/online/book/store/model/ShoppingCart.java
> +    @NotNull
```suggestion
```

2024-05-08 12:51 UTC, kerrrusha commented on src/main/java/online/book/store/repository/ShoppingCartRepository.java
> +
```suggestion
```

2024-05-08 17:14 UTC, aksoli666 commented on src/main/java/online/book/store/repository/ShoppingCartRepository.java
> +
Why do i need to remove this interfaces? i am using it

2024-05-09 06:49 UTC, Elena-Bruyako requested changes
Need to watch video and lecture again and implement the right logic

2024-05-09 06:49 UTC, Elena-Bruyako commented on src/main/java/online/book/store/controller/CartController.java
> +    public ShoppingCartAddBookDto addBook(
```suggestion
    public ShoppingCartDto addBook(Authentication authentication,
                                   @RequestBody @Valid CartItemRequestDto cartItem)
```

2024-05-09 06:49 UTC, Elena-Bruyako commented on src/main/java/online/book/store/controller/CartController.java
> +        return cartService.addBook(shoppingCartDto, itemCartDto);
```suggestion
        User user = (User) authentication.getPrincipal();
        return cartService.addBookToCart(user.getId(), cartItem);
```

2024-05-09 06:49 UTC, Elena-Bruyako commented on src/main/java/online/book/store/controller/CartController.java
> +    @PutMapping
```suggestion
    @PutMapping("/cart-items/{cartItemId}")
```

2024-05-09 06:49 UTC, Elena-Bruyako commented on src/main/java/online/book/store/controller/CartController.java
> +    public void updateCartItem(Long id, int quantity) {
```suggestion
    public void updateCartItem(Authentication authentication,
                                              @PathVariable @Positive Long cartItemId,
                                              @RequestBody @Valid UpdateCartItemDto item) {
```

This method should return updated shopping cart

2024-05-09 06:49 UTC, Elena-Bruyako commented on src/main/java/online/book/store/controller/CartController.java
> +        cartService.updateCartItem(id, quantity);
```suggestion
        User user = (User) authentication.getPrincipal();
        return cartService.updateBookQuantity(user.getId(), cartItemId, item);
```

2024-05-09 06:49 UTC, Elena-Bruyako commented on src/main/java/online/book/store/controller/CartController.java
> +    @DeleteMapping
```suggestion
    @DeleteMapping("/cart-items/{cartItemId}")
```

2024-05-09 06:49 UTC, Elena-Bruyako commented on src/main/java/online/book/store/controller/CartController.java
> +    public void deleteBook(Long id, CartItemDeleteBookDto deleteBookDto) {
Did you check your endpoint? Can you provide id or dto object?

2024-05-09 06:49 UTC, Elena-Bruyako commented on src/main/java/online/book/store/controller/CartController.java
> +    public void deleteBook(Long id, CartItemDeleteBookDto deleteBookDto) {
```suggestion
    public void deleteBook(Authentication authentication,
                                            @PathVariable @Positive Long cartItemId) {
```

2024-05-09 06:49 UTC, Elena-Bruyako commented on src/main/java/online/book/store/controller/CartController.java
> +        cartService.deleteBook(id, deleteBookDto);
```suggestion
        User user = (User) authentication.getPrincipal();
        cartService.deleteBookFromCart(user.getId(), cartItemId);
```

2024-05-09 06:49 UTC, Elena-Bruyako commented on src/main/java/online/book/store/mapper/CartMapper.java
> +    CartItemDto toDto(CartItem cartItem);
It's not related to CartMapper

2024-05-09 06:49 UTC, Elena-Bruyako commented on src/main/java/online/book/store/mapper/CartMapper.java
> +    CartItem toModel(ItemCartAddBookRequestDto requestDto);
the same as above

2024-05-09 06:49 UTC, Elena-Bruyako commented on src/main/java/online/book/store/mapper/CartMapper.java
> +    CartItem toModel(CartItemDto cartItemDto);
the same as above

2024-05-09 06:49 UTC, Elena-Bruyako commented on src/main/java/online/book/store/model/CartItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "shopping_cart_id", nullable = false)
```

2024-05-09 06:49 UTC, Elena-Bruyako commented on src/main/java/online/book/store/model/CartItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "book_id", nullable = false)
```

2024-05-09 06:49 UTC, Elena-Bruyako commented on src/main/java/online/book/store/model/ShoppingCart.java
> +    @OneToOne
```suggestion
    @OneToOne(fetch = FetchType.LAZY)
```

2024-05-09 06:49 UTC, Elena-Bruyako commented on src/main/java/online/book/store/model/ShoppingCart.java
> +    @OneToMany(mappedBy = "shoppingCart")
```suggestion
    @OneToMany(mappedBy = "shoppingCart", cascade = CascadeType.ALL, orphanRemoval = true)
```

2024-05-09 06:49 UTC, Elena-Bruyako commented on src/main/java/online/book/store/repository/BookRepository.java
> +    List<Book> findBooksByCategoryId(Long categoryId);
I didn't find any logic related to Category. Don't need to create PR with several solutions

2024-05-09 06:49 UTC, Elena-Bruyako commented on src/main/java/online/book/store/repository/ShoppingCartRepository.java
> +
You don't need to remove nothing here, just blank line

2024-05-09 06:49 UTC, Elena-Bruyako commented on src/main/java/online/book/store/service/impl/CartServiceImpl.java
> +        return shoppingCartDto;
Would you like to save the book into DB? What if this book is absent in DB? 
Please, implement the logic according to the lecture and video

2024-05-09 19:45 UTC, sarakhmen approved these changes
lgtm!

2024-05-11 08:42 UTC, merged