Tests
aksoli666/online-book-store pull request #18
Opened 2024-06-11 07:33 UTC by aksoli666

+Added test cases for Book and Category entities 
(repository, service, controller).
![Знімок екрана 2024-06-11 092207](https://github.com/aksoli666/online-book-store/assets/121487293/318420c2-504b-4534-af64-b540218d1dbe)

2024-06-11 08:20 UTC, Elena-Bruyako requested changes
good job

2024-06-11 08:20 UTC, Elena-Bruyako commented on src/main/java/online/book/store/config/SecurityConfig.java
>  @EnableWebSecurity
Do we need both of `@EnableMethodSecurity and @EnableWebSecurity` here?

2024-06-11 08:20 UTC, Elena-Bruyako commented on src/main/java/online/book/store/repository/UserRepository.java
> +    @Query(value = "SELECT u FROM User u LEFT JOIN FETCH u.roles where u.email = :email")
```suggestion
    @EntityGraph(attributePaths = "roles")
```

2024-06-11 08:20 UTC, Elena-Bruyako commented on src/main/java/online/book/store/service/impl/UserServiceImpl.java
> +        user.setPassword(passwordEncoder.encode(userRequestDto.getPassword()));
```suggestion
        user.setPassword(passwordEncoder.encode(userRequestDto.getPassword()));
        user.setRole....
```

2024-06-11 08:20 UTC, Elena-Bruyako commented on src/test/java/online/book/store/controller/BookControllerTest.java
> +        Arrays.stream(actual).forEach(System.out::println);
Do we need this?

2024-06-11 08:20 UTC, Elena-Bruyako commented on src/test/java/online/book/store/service/BookServiceTest.java
> +        Assertions.assertThat(savedBookDto).isEqualTo(bookDto);
```suggestion
        assertEquals(bookDto, savedBookDto);
```

2024-06-11 08:20 UTC, Elena-Bruyako commented on src/test/java/online/book/store/service/BookServiceTest.java
> +        Assertions.assertThat(savedBookDto).isEqualTo(bookDto);
Check other places

2024-06-11 17:07 UTC, Vasul-Pankiv requested changes

2024-06-11 17:07 UTC, Vasul-Pankiv commented on src/test/resources/database/online-book-store/book/add-book-for-update.sql
> +insert into books (id, title, author, isbn, price, description, cover_image, user_id) values (8, "Title8", "Author8", "isbn8", 58, "description8", "cover img8", 1);
all files has to end with empty line

2024-06-11 17:07 UTC, Vasul-Pankiv commented on src/test/java/online/book/store/service/BookServiceTest.java
> +        Book book1 = new Book();
try to create BookProvider class with static method to get needed books

2024-06-11 17:07 UTC, Vasul-Pankiv commented on src/test/java/online/book/store/service/BookServiceTest.java
> +        Book book1 = new Book();
it's up to you

2024-06-12 09:59 UTC, Elena-Bruyako commented on src/test/resources/database/online-book-store/book/add-book-for-update.sql
> +insert into books (id, title, author, isbn, price, description, cover_image, user_id) values (8, "Title8", "Author8", "isbn8", 58, "description8", "cover img8", 1);
Not fixed

2024-06-12 10:00 UTC, Elena-Bruyako requested changes
Please, fix comment that mentor left

2024-06-12 10:50 UTC, aksoli666 commented
> Please, fix comment that mentor left
To create a BookProvider class was a wish, and in the files I added empty lines

2024-06-12 17:13 UTC, Vasul-Pankiv approved these changes

2024-06-13 10:08 UTC, merged